---
ansible_user_home: /home/ansibleuser
script_path: /opt/app/

# JDK 8 variables
jdk_8_url: "https://oneartifactory.horizon.com/artifactory/software/jdk-8u461-linux-x64.tar.gz"
jdk_8_tar: "jdk-8u461-linux-x64.tar.gz"
jdk_8_version_old: "jdk1.8.0_451"
jdk_8_version_new: "jdk1.8.0_461"
jdk_8_link: "JDK"

# JDK 17 variables
jdk_17_url: "https://oneartifactory.horizon.com/artifactory/software/jdk-17.0.16_linux-x64_bin.tar.gz"
jdk_17_tar: "jdk-17.0.16_linux-x64_bin.tar.gz"
jdk_17_version_old: "jdk-17.0.15"
jdk_17_version_new: "jdk-17.0.16"
jdk_17_link: "jdk17"

# Authentication variables
auth_user: "jenkins-build"
auth_pass: "your-secure-token"
